const dadosMedicamento =  [
    {
        "id": 1, 
        "nome": "Paracetamol 500mg (20 comp.)",
        "preco": "R$ 8,90",
        "img": require('@/assets/paracetamol.jpg'), 
        "tipo": "Analgésicos",
        "descricao": "Analgésico e antitérmico de uso comum. Indicado para o alívio de dores leves a moderadas, como dor de cabeça, e para reduzir a febre.",
        "alertaAlergia": "Reações alérgicas (erupção cutânea, coceira) são raras, mas possíveis. Não exceder a dose máxima diária.",
        "receitaObrigatoria": false,
    },
    {
        "id": 2,
        "nome": "Vitamina C 1g (30 comp.)",
        "preco": "R$ 29,90",
        "img": require('@/assets/VitaminaC.jpg'),
        "tipo": "Vitaminas",
        "descricao": "Suplemento de vitamina C que auxilia no fortalecimento do sistema imunológico, absorção de ferro e tem ação antioxidante.",
        "alertaAlergia": "Pode causar desconforto gástrico em altas doses. Não exceder a dose recomendada sem orientação médica.",
        "receitaObrigatoria": false,
    },
    {
        "id": 3,
        "nome": "Ibuprofeno 400mg (10 cáp.)",
        "preco": "R$ 15,45",
        "img": require('@/assets/Ibuprofeno.jpg'),
        "tipo": "Anti-inflamatórios",
        "descricao": "Medicamento com ação anti-inflamatória, analgésica e antitérmica. Alivia dores e combate inflamações.",
        "alertaAlergia": "Evitar em casos de úlcera gástrica ou problemas renais. Pode causar reações de hipersensibilidade.",
        "receitaObrigatoria": false,
    },
    {
        "id": 4,
        "nome": "Pomada Cicatrizante 50g",
        "preco": "R$ 34,90",
        "img": require('@/assets/PomadaCicatrizante.jpg'),
        "tipo": "Dermatológicos",
        "descricao": "Pomada indicada para o tratamento de feridas leves, queimaduras e para acelerar o processo natural de cicatrização da pele.",
        "alertaAlergia": "Em caso de irritação ou vermelhidão excessiva, suspenda o uso e procure um médico.",
        "receitaObrigatoria": false,
    },
    {
        "id": 5,
        "nome": "Chá Calmante Natural (20 sachês)",
        "preco": "R$ 19,90",
        "img": require('@/assets/ChaCalmanteNatural.jpg'),
        "tipo": "Fitoterápicos",
        "descricao": "Mistura de ervas naturais que ajudam a reduzir a ansiedade e promovem o relaxamento. Ideal para consumo antes de dormir.",
        "alertaAlergia": "Pode causar sonolência. Não recomendado para gestantes e lactantes sem orientação médica.",
        "receitaObrigatoria": false,
    },
    {
        "id": 6,
        "nome": "Dorflex (10 comp.)",
        "preco": "R$ 12,99",
        "img": require('@/assets/Dorflex.jpg'),
        "tipo": "Analgésicos",
        "descricao": "Analgésico e relaxante muscular. Indicado para o alívio de dores de cabeça tensionais e dores musculares.",
        "alertaAlergia": "Pode causar tontura e reações alérgicas. O uso prolongado deve ser evitado.",
        "receitaObrigatoria": false,
    },
    {
        "id": 7,
        "nome": "Polivitamínico AZ (60 comp.)",
        "preco": "R$ 49,99",
        "img": require('@/assets/Polivitaminico.jpg'),
        "tipo": "Vitaminas",
        "descricao": "Suplemento completo com vitaminas e minerais de A a Z. Auxilia na manutenção da saúde e energia diária.",
        "alertaAlergia": "Não existem alertas graves. Apenas manter fora do alcance de crianças e não exceder a dose.",
        "receitaObrigatoria": false,
    },
    {
        "id": 8,
        "nome": "Creme Hidratante Pós-sol",
        "preco": "R$ 22,50",
        "img": require('@/assets/cremeHidratantePosSol.jpg'),
        "tipo": "Dermatológicos",
        "descricao": "Creme refrescante para aliviar a ardência e hidratar a pele após a exposição solar. Contém Aloe Vera.",
        "alertaAlergia": "Em raros casos pode haver hipersensibilidade a um dos componentes. Uso tópico.",
        "receitaObrigatoria": false,
    },
    {
        "id": 9,
        "nome": "Aspirina 100mg (10 comp.)",
        "preco": "R$ 9,90",
        "img": require('@/assets/Aspirina.jpg'),
        "tipo": "Analgésicos",
        "descricao": "Ácido acetilsalicílico em baixa dosagem, usado para prevenir a formação de coágulos e tratar dores leves.",
        "alertaAlergia": "Pode irritar o estômago e causar sangramento. Contraindicado para crianças com sintomas gripais e pessoas com hemofilia.",
        "receitaObrigatoria": false,
    },
    {
        "id": 10,
        "nome": "Melatonina 3mg (30 cáp.)",
        "preco": "R$ 55,00",
        "img": require('@/assets/Melatonina.jpg'),
        "tipo": "Fitoterápicos",
        "descricao": "Hormônio que regula o ciclo do sono. Auxilia na indução e melhoria da qualidade do sono em casos de insônia.",
        "alertaAlergia": "Pode causar sonolência diurna ou tonturas. Evitar dirigir ou operar máquinas após o uso.",
        "receitaObrigatoria": false,
    },
    {
        "id": 11,
        "nome": "Amoxicilina 500mg (21 comp.)",
        "preco": "R$ 38,00",
        "img": require('@/assets/Amoxicilina.jpg'),
        "tipo": "Anti-inflamatórios",
        "descricao": "Antibiótico de amplo espectro, utilizado no tratamento de diversas infecções bacterianas. Requer diagnóstico médico.",
        "alertaAlergia": "Risco de reações alérgicas graves (choque anafilático) em pacientes sensíveis à penicilina. Uso restrito à prescrição.",
        "receitaObrigatoria": true,
    },
    {
        "id": 12,
        "nome": "Probiótico Ativo (10 cáp.)",
        "preco": "R$ 68,00",
        "img": require('@/assets/probioticoAtivo.jpg'),
        "tipo": "Vitaminas",
        "descricao": "Suplemento com culturas ativas de bactérias benéficas para equilibrar a flora intestinal e melhorar a digestão.",
        "alertaAlergia": "Geralmente seguro. Em casos raros pode causar inchaço ou gases leves no início do tratamento.",
        "receitaObrigatoria": false,
    },
    {
        "id": 13,
        "nome": "Cetoprofeno 150mg (10 cápsulas)",
        "preco": "R$ 35,00",
        "img": require('@/assets/cetoprofeno.jpg'),
        "tipo": "Anti-inflamatório",
        "descricao": "Potente anti-inflamatório e analgésico, usado para dor intensa, reumatismo e traumatismos.",
        "alertaAlergia": "Alto risco de irritação gástrica e reações alérgicas. Uso estrito sob prescrição médica.",
        "receitaObrigatoria": true,
    },
    {
        "id": 14,
        "nome": "Ácido Acetilsalicílico (AAS) 500mg (20 comp)",
        "preco": "R$ 6,50",
        "img": require('@/assets/ass.jpg'),
        "tipo": "Analgésico",
        "descricao": "Alívio de dores leves, febre. Em doses baixas, usado como antiagregante plaquetário.",
        "alertaAlergia": "Pode causar Síndrome de Reye em crianças e agravar úlceras. Não usar em caso de dengue.",
        "receitaObrigatoria": false,
    },
    {
        "id": 15,
        "nome": "Diclofenaco Sódico 50mg (20 comp)",
        "preco": "R$ 11,20",
        "img": require('@/assets/diclofenaco.jpg'),
        "tipo": "Anti-inflamatório",
        "descricao": "Tratamento de dor e inflamação, como artrite, tendinite e dor pós-operatória.",
        "alertaAlergia": "Contraindicado para pacientes com histórico de problemas cardíacos ou renais graves.",
        "receitaObrigatoria": false,
    },
    {
        "id": 16,
        "nome": "Tylenol Sinus (Paracetamol + Descongestionante)",
        "preco": "R$ 28,90",
        "img": require('@/assets/tylenolsinus.jpg'),
        "tipo": "Analgésico",
        "descricao": "Alívio de sintomas de gripe e resfriado, como dor de cabeça, febre e congestão nasal.",
        "alertaAlergia": "Usar com cautela em pacientes com pressão alta ou glaucoma devido ao descongestionante.",
        "receitaObrigatoria": false,
    },
    {
    "id": 17,
    "nome": "Ômega 3-3 unidades de 120 cápsulas - Catarinense",
    "preco": "R$ 25,90",
    "img": require('@/assets/omega3.jpg'),
    "tipo": "Vitaminas",
    "descricao": "Auxilia na defesa do organismo, na absorção de ferro e tem ação antioxidante.",
    "alertaAlergia": "Pode causar diarreia em altas doses. Não exceder a dose diária recomendada.",
    "receitaObrigatoria": false,
  },
  {
    "id": 18,
    "nome": "Vitamina D 2.000 UI (30 cápsulas)",
    "preco": "R$ 39,90",
    "img": require('@/assets/vitaminaD.jpg'),
    "tipo": "Vitaminas",
    "descricao": "Essencial para a saúde óssea e o sistema imunológico. Auxilia na absorção de cálcio.",
    "alertaAlergia": "Risco de toxicidade (hipercalcemia) em superdosagem. Usar sob orientação profissional.",
    "receitaObrigatoria": false,
  },
  {
    "id": 19,
    "nome": "Complexo B (B1, B6, B12) (60 cápsulas)",
    "preco": "R$ 35,50",
    "img": require('@/assets/complexoB.jpg'),
    "tipo": "Vitaminas",
    "descricao": "Auxilia no metabolismo energético, na saúde dos nervos e na formação de células vermelhas.",
    "alertaAlergia": "Pode causar coloração amarelada na urina (efeito normal).",
    "receitaObrigatoria": false,
  },
  {
    "id": 20,
    "nome": "Vitamina A + E (30 cápsulas)",
    "preco": "R$ 48,00",
    "img": require('@/assets/vitaminaAE.jpg'),
    "tipo": "Vitaminas",
    "descricao": "Combinação de vitaminas com alto poder antioxidante, importante para a visão e pele.",
    "alertaAlergia": "O excesso de Vitamina A pode ser tóxico (hipervitaminose A). Uso com cautela.",
    "receitaObrigatoria": false,
  },
  {
    "id": 21,
    "nome": "Polivitamínico (A a Z) (60 cápsulas)",
    "preco": "R$ 55,00",
    "img": require('@/assets/polivitaminicoAZ.jpg'),
    "tipo": "Vitaminas",
    "descricao": "Suplemento completo para complementar a dieta com micronutrientes essenciais.",
    "alertaAlergia": "Contém ferro; manter fora do alcance de crianças para evitar intoxicação acidental.",
    "receitaObrigatoria": false,
  },
  {
    "id": 22,
    "nome": "Miconazol 2% Creme (30g)",
    "preco": "R$ 18,50",
    "img": require('@/assets/miconazol.jpg'),
    "tipo": "Dermatológicos",
    "descricao": "Tratamento de micoses de pele e unhas, como Tinea pedis (pé de atleta).",
    "alertaAlergia": "Uso externo. Evitar contato com os olhos. Interromper se houver irritação.",
    "receitaObrigatoria": false,
  },
  {
    "id": 23,
    "nome": "Hidrocortisona 1% Pomada (15g)",
    "preco": "R$ 25,00",
    "img": require('@/assets/hidrocortisona.jpg'),
    "tipo": "Dermatológicos",
    "descricao": "Alívio de coceira, vermelhidão e inchaço causados por dermatites e picadas de inseto.",
    "alertaAlergia": "Não usar em grandes áreas da pele ou por tempo prolongado sem orientação médica. Não usar em infecções fúngicas ativas.",
    "receitaObrigatoria": false,
  },
  {
    "id": 24,
    "nome": "Permetrina 5% Loção (60ml)",
    "preco": "R$ 45,00",
    "img": require('@/assets/permetrina.jpg'),
    "tipo": "Dermatológicos",
    "descricao": "Tratamento de escabiose (sarna) e pediculose (piolhos).",
    "alertaAlergia": "Pode causar ardência temporária. Manter longe de olhos e mucosas.",
    "receitaObrigatoria": false,
  },
  {
    "id": 25,
    "nome": "Ácido Fusídico Creme (15g)",
    "preco": "R$ 58,00",
    "img": require('@/assets/acidofusidico.jpg'),
    "tipo": "Dermatológicos",
    "descricao": "Tratamento tópico de infecções da pele causadas por bactérias sensíveis.",
    "alertaAlergia": "Pode causar reações de hipersensibilidade. Uso restrito e sob prescrição.",
    "receitaObrigatoria": true,
  },
  {
    "id": 26,
    "nome": "Peróxido de Benzoíla 5% Gel (20g)",
    "preco": "R$ 32,50",
    "img": require('@/assets/peroxidobenzoila.jpg'),
    "tipo": "Dermatológicos",
    "descricao": "Tratamento da acne leve a moderada. Possui ação bactericida e esfoliante.",
    "alertaAlergia": "Pode causar ressecamento e vermelhidão no início do tratamento. Evitar exposição solar.",
    "receitaObrigatoria": false,
  },
  {
    "id": 27,
    "nome": "Passiflora incarnata (60 cápsulas)",
    "preco": "R$ 29,90",
    "img": require('@/assets/passiflora.jpg'),
    "tipo": "Fitoterápicos",
    "descricao": "Tradicionalmente usado no tratamento de estados de ansiedade, nervosismo e insônia leve.",
    "alertaAlergia": "Pode causar sonolência. Não é recomendado o uso concomitante com bebidas alcoólicas.",
    "receitaObrigatoria": false,
  },
  {
    "id": 28,
    "nome": "Ginkgo biloba 80mg (30 comp)",
    "preco": "R$ 38,00",
    "img": require('@/assets/ginkgobiloba.jpg'),
    "tipo": "Fitoterápicos",
    "descricao": "Auxilia na melhora da circulação sanguínea, memória e combate vertigem.",
    "alertaAlergia": "Consultar médico se usar medicamentos anticoagulantes, devido ao risco de sangramento.",
    "receitaObrigatoria": false,
  },
  {
    "id": 29,
    "nome": "Harpagophytum procumbens (30 cápsulas)",
    "preco": "R$ 42,00",
    "img": require('@/assets/harpago.jpg'),
    "tipo": "Fitoterápicos",
    "descricao": "Indicado como anti-inflamatório e para o alívio de dores articulares e reumáticas.",
    "alertaAlergia": "Contraindicado para pacientes com úlceras gástricas ou intestinais.",
    "receitaObrigatoria": false,
  },
  {
    "id": 30,
    "nome": "Ptychopetalum olacoides (Muirapuama) (60 cápsulas)",
    "preco": "R$ 55,00",
    "img": require('@/assets/muirapuama.jpg'),
    "tipo": "Fitoterápicos",
    "descricao": "Utilizado popularmente como tônico, estimulante e afrodisíaco.",
    "alertaAlergia": "Não usar em caso de hipersensibilidade ou em doses elevadas. Consulte um profissional.",
    "receitaObrigatoria": false,
  },
  {
    "id": 31,
    "nome": "Silybum marianum (Cardo Mariano) (30 comp)",
    "preco": "R$ 49,90",
    "img": require('@/assets/cardomariano.jpg'),
    "tipo": "Fitoterápicos",
    "descricao": "Usado para proteger o fígado e auxiliar no tratamento de distúrbios hepáticos leves.",
    "alertaAlergia": "Pode causar efeito laxante leve. Não usar em caso de obstrução das vias biliares.",
    "receitaObrigatoria": false,
  },
  {
    "id": 32,
    "nome": "Cetoprofeno 150mg (10 cápsulas)",
    "preco": "R$ 35,00",
    "img": require('@/assets/cetoprofeno_extra.jpg'),
    "tipo": "Anti-inflamatórios",
    "descricao": "Potente anti-inflamatório e analgésico, usado para dor intensa, reumatismo e traumatismos.",
    "alertaAlergia": "Alto risco de irritação gástrica e reações alérgicas. Uso estrito sob prescrição médica.",
    "receitaObrigatoria": true,
  },
  {
    "id": 33,
    "nome": "Ácido Acetilsalicílico (AAS) 500mg (20 comp)",
    "preco": "R$ 6,50",
    "img": require('@/assets/aas_extra.jpg'),
    "tipo": "Anti-inflamatórios",
    "descricao": "Alívio de dores leves, febre. Em doses baixas, usado como antiagregante plaquetário.",
    "alertaAlergia": "Pode causar Síndrome de Reye em crianças e agravar úlceras. Não usar em caso de dengue.",
    "receitaObrigatoria": false,
  },
  {
    "id": 34,
    "nome": "Diclofenaco Sódico 50mg (20 comp)",
    "preco": "R$ 11,20",
    "img": require('@/assets/diclofenaco_extra.jpg'),
    "tipo": "Anti-inflamatórios",
    "descricao": "Tratamento de dor e inflamação, como artrite, tendinite e dor pós-operatória.",
    "alertaAlergia": "Contraindicado para pacientes com histórico de problemas cardíacos ou renais graves.",
    "receitaObrigatoria": false,
  },
  {
    "id": 35,
    "nome": "Tylenol Sinus (Paracetamol + Descongestionante)",
    "preco": "R$ 28,90",
    "img": require('@/assets/tylenolsinus_extra.jpg'),
    "tipo": "Anti-inflamatórios",
    "descricao": "Alívio de sintomas de gripe e resfriado, como dor de cabeça, febre e congestão nasal.",
    "alertaAlergia": "Usar com cautela em pacientes com pressão alta ou glaucoma devido ao descongestionante.",
    "receitaObrigatoria": false,
  },
  {
    "id": 36,
    "nome": "Sulfato Ferroso 40mg (Ferro Elementar) (30 comp)",
    "preco": "R$ 14,90",
    "img": require('@/assets/sulfatoferroso.jpg'),
    "tipo": "Vitaminas",
    "descricao": "Prevenção e tratamento da anemia ferropriva (deficiência de ferro).",
    "alertaAlergia": "Pode causar dor de estômago e fezes escuras. Não usar em caso de anemias não causadas por deficiência de ferro.",
    "receitaObrigatoria": false,
  },
]
export default dadosMedicamento;